### ISSUE TITLE
Bug Report: Unclickable Screen after Adapter Selection - Fixed 

### ISSUE THREAD

**Issue by DevSirius-bit** [im-kuro/piWardriving#1]
### Bug Report
_Type: Non-Fatal; Visual_
- After a user selects a screen, there is a high chance the screen will darken and become un-clickable as if the prompt itself never disappeared. Believed to be a simple communication issue between the styling, still looking into it
- Work-around: Refresh page, adapter should save and panel will work fine

_Both systems were using latest version of Mozilla Firefox_

**Comment by im-kuro** [comment]
Thanks for reporting, i can recreate this by restarting the server, looking into it asap.
![image](https://github.com/im-kuro/piWardriving/assets/86091489/ef5f25af-b03f-4649-9262-fa1ce4588215)

**Comment by im-kuro** [comment]
seems to be a js issue making a new div at the bottom with the class "modal-backdrop show". working on it now



![image](https://github.com/im-kuro/piWardriving/assets/86091489/90fc4c53-d090-4778-a48b-6d37813b8581)

**Comment by im-kuro** [comment]
@LovelyNukie new push should fix it, lmk if you have any issues
